# Generated by Django 4.1.4 on 2023-02-25 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=500)),
                ('user_code', models.CharField(max_length=3)),
                ('mobile', models.CharField(max_length=15)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_reg.city')),
            ],
        ),
    ]
