# Generated by Django 4.1.4 on 2023-02-28 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_reg', '0002_remove_user_fullname_remove_user_user_code_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='City',
            new_name='Relation',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='city',
            new_name='relation',
        ),
    ]
