# Generated by Django 4.1.4 on 2023-02-28 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_reg', '0003_rename_city_relation_rename_city_user_relation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
    ]
