# Generated by Django 4.1.4 on 2023-03-02 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_reg', '0005_alter_user_firstname_alter_user_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='relation',
        ),
        migrations.DeleteModel(
            name='Relation',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
