# Generated by Django 4.1.7 on 2023-03-11 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_reg', '0006_remove_user_relation_delete_relation_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15)),
                ('fname', models.CharField(max_length=15)),
                ('lname', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=15)),
                ('password', models.CharField(max_length=8)),
                ('re_password', models.CharField(max_length=8)),
            ],
        ),
    ]
